import Head from "next/head";
import Image from "next/image";
import ImagePreview from "../public/image-preview.jpg";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="flex">
          <div className="col h-100">
            <div className="flex mt-0">
              <div className="flex_thumbnail">
                <div className="thumbnail">
                  <Image
                    src={ImagePreview}
                    layout="fixed"
                    alt="Image Preview alt text"
                    placeholder="blur"
                    width={67}
                    height={100}
                  />
                </div>
                <div className="thumbnail active">
                  <Image
                    src={ImagePreview}
                    layout="fixed"
                    alt="Image Preview alt text"
                    placeholder="blur"
                    width={67}
                    height={100}
                  />
                </div>
                <div className="thumbnail">
                  <Image
                    src={ImagePreview}
                    layout="fixed"
                    alt="Image Preview alt text"
                    placeholder="blur"
                    width={67}
                    height={100}
                  />
                </div>
              </div>
              <div className="image-preview" style={{ flex: 2 }}>
                <Image
                  src={ImagePreview}
                  layout="intrinsic"
                  alt="Image Preview alt text"
                  placeholder="blur"
                  width={550}
                  height={850}
                  className="img-view"
                />
              </div>
            </div>
          </div>
          <div className="col">
            <div style={{ display: "block" }}>
              <h1 className="title">Host Lequite Artistic</h1>
              <small>
                <span style={{ fontSize: "1.2rem" }}>Formal Wears</span> •{" "}
                <span>Available</span> • <span>100% Cotton</span>
              </small>

              <div className="selector">
                <p className="header">Select Color</p>
                <div className="radio">
                  <label className="input" htmlFor="1"></label>
                  <input type="radio" id="1" name="color" />
                  <label className="input" htmlFor="2"></label>
                  <input type="radio" id="2" name="color" />
                  <label className="input" htmlFor="3"></label>
                  <input type="radio" id="3" name="color" />
                </div>
              </div>
              <div className="selector">
                <p className="header">Select Size</p>
                <div className="size">
                  <button disabled>32</button>
                  <button>42</button>
                  <button>56</button>
                  <button className="active">12</button>
                </div>
              </div>
              <p className="description">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis
                voluptatem voluptas odio laudantium? Ab commodi incidunt aliquid
                nihil? Atque quae officia dicta temporibus autem, distinctio ea
                accusamus maiores quia perferendis. Lorem ipsum, dolor sit amet
                consectetur adipisicing elit. Omnis voluptatem voluptas odio
                laudantium? Ab commodi incidunt aliquid nihil? Atque quae
                officia dicta temporibus autem, distinctio ea accusamus maiores
                quia perferendis.
              </p>
              <div className="options">
                <button>Option 1</button>
                <button>Option 2</button>
                <button>Option 3</button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
